services:
  backend:
    build: ./backend
    container_name: hirere_api
    ports:
      - "7777:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hirere
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: hirere_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: hirere_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hirere
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
